{
  "development": {
    "username": "eventbuddy",
    "password": "secret",
    "database": "eventbuddy_db",
    "host": "localhost",   
    "port": 5432,
    "dialect": "postgres"
  },
  "test": {
    "username": "eventbuddy",
    "password": "secret",
    "database": "eventbuddy_db_test",
    "host": "localhost",
    "port": 5432,
    "dialect": "postgres"
  },
  "production": {
    "username": "eventbuddy",
    "password": "secret",
    "database": "eventbuddy_db",
    "host": "localhost",
    "port": 5432,
    "dialect": "postgres"
  }
}
