version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: eventbuddy_db
    restart: always
    environment:
      POSTGRES_USER: eventbuddy
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: eventbuddy_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
